name: Deploy backend-mongp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Directory Permissions
        run: chmod -R 775 storage bootstrap/cache
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.sftp_host }}
          username: ${{ secrets.sftp_user }}
          password: ${{ secrets.sftp_password }}
          server-dir: "/sites/backend-mongp.mayaapps.site/"
          exclude: |
            **/.github/**
            **/.releases/**
            **/.git/**
            **/node_modules/**
            **/vendor/**
            **/storage/*.key
            **/.env
            **/public/build
            **/storage/dbdata/*
            **/.phpunit.cache
            **/public/storage
            **/.env.backup
            **/.env.production
            **/composer.lock

      - name: SSH into the production server and restart PM2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.sftp_host }}
          username: ${{ secrets.sftp_user }}
          password: ${{ secrets.sftp_password }}
          port: 22
          script: |
            cd sites/backend-mongp.mayaapps.site
            composer update
            composer install
            php artisan migrate
            php artisan storage:link
            
